import Loader from "@/components/layout/Loader";
import "./scss/index/globals.scss";
import "@fontsource/open-sans";
import Header from "@/components/layout/header/Header";
import Splash from "@/components/layout/Splash";

export const metadata = {
  title: "TanwishLife",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <Loader />
          <Splash />
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
